#!/usr/bin/env python
# coding=utf-8
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.ticker import MaxNLocator
from collections import namedtuple


# 7种表情
n_groups = 7

values = [[61.1, 67.3, 49.5, 88.7, 65.2, 83.2, 69.2], #{} 会导致这被看作是集合,不是list,无序
          [60.92, 67.27, 49.41, 88.69, 65.07, 82.83, 69.08],
          [61.12, 67.27, 49.41, 88.69, 65.23, 83.08, 69.24],
          [61.32, 69.09, 49.61, 89.02, 65.56, 83.59, 69.73], 
          [67.74, 74.54, 56.25, 95.56, 65.57, 89.65, 75.85]
          ]


fig, ax = plt.subplots()
index = np.arange(n_groups)
bar_width = 0.35
classes = ('Angry', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral')
labels = ('ReLu', 'P-ReLu', 'L-ReLu', 'Swish', 'Swish+')
colors = ('Red', 'Blue', 'Yellow', 'Silver', 'grey', 'Brown', 'Green')
#for x in range(0,6,1):
rects = ax.bar(index+index*bar_width, values, bar_width,color =colors, label=labels)



ax.set_xlabel('Emotions')
ax.set_ylabel('Accuracy')
ax.set_title('Accuracy on different Emotions')
ax.set_xticks(index + bar_width / 2)
ax.set_xticklabels(classes)
ax.legend("upper right")


fig.tight_layout()
plt.show()

